# -*- coding: utf-8 -*-
"""model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzBPZ5KA0oWlXfjPcX8BWV6ujj2hHU5z
"""

import pandas as pd
import numpy as np

# import logistic regression classifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

# import grid search and cross-validation
from sklearn.model_selection import GridSearchCV

# import auc metric
from sklearn.metrics import roc_auc_score

lend_df = pd.read_csv('https://raw.githubusercontent.com/MattDBailey/ANOP330Module_LoanDefaultPredictor-Streamlit/refs/heads/main/LendingClub_DataSet.csv')
lend_df.head(10)

# Separate into predictors (X) and a SINGLE TARGET outcome (Y)
X = lend_df.drop('loan_status', axis=1)
y = lend_df.loan_status

# Create a train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, train_size=.8)

# Use GridSearchCV to find the best parameters for logistidc regression
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}

# Use GridSearchCV to find the best parameters for Logistic regression
gridSearch_auc = GridSearchCV(estimator=LogisticRegression(random_state=1), param_grid=param_grid, cv=5, scoring='roc_auc', n_jobs=1, verbose=1)
gridSearch_auc.fit(X_train, y_train)
print('Initial score: {:.2f}'.format(gridSearch_auc.best_score_))
print('Best parameters from param_grid: {}'.format(gridSearch_auc.best_params_))

# Fit the model with the best parameters
BestLogReg = gridSearch_auc.best_estimator_

# Check the auc using the test data
test_pred_prob = BestLogReg.predict_proba(X_test)[:,1]
test_auc = roc_auc_score(y_test, test_pred_prob)
print('Test AUC: {:.2f}'.format(test_auc))

# Write a file of binary model ('wb') (=dump) to a file using pickle
import pickle
filename = 'model.pkl'
with open(filename, 'wb') as file:
    pickle.dump(BestLogReg, file)

# Open the file and load the model
file_to_load = 'model.pkl'
with open(file_to_load, 'rb') as file:
    loaded_model = pickle.load(file)

# Create a new customer
ownhome = 1  # 1 for own home, 0 for rent
income = 80000  # annual income
dti = 0.2  # debt-to-income ratio
fico = 700  # FICO score

# Create a dataframe for the new customer
# Make sure the ORDER of the columns is the same as in the training data
# Note: The column names should match the training data columns
new_customer = pd.DataFrame({
    'home_ownership': [ownhome],
    'income': [income],
    'dti': [dti],
    'fico': [fico]
})

# Print the predicted probability of default
predicted_prob = loaded_model.predict_proba(new_customer)[:, 0]
print('Predicted probability of default: {:.2f}'.format(predicted_prob[0]))
# Print the predicted class
predicted_class = loaded_model.predict(new_customer)
# print 'Predicted to Default' if predicted_class[0] == 1 else 'Predicted to not Default'
if predicted_class[0] == 0:
    print('Predicted class: Default')
else:
    print('Predicted class: Not Default')